### ISSUE TITLE
The last commit seems to be causing errors on restoring the checkpoint.

### ISSUE THREAD

**Issue by YongtaeKim** [AdalbertoCq/Pathology-GAN#10]
#### Running the "generate_fake_samples.py" with the provided checkpoint file is producing no images with following error messages.

```
NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key generator/attention_block_2/conv_layer_1/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/user1/Pathology-GAN/models/evaluation/features.py:196)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```

#### Temporary fix - Simply change the following line which appears twice in "models/generative/generator.py":
net = attention_block(net, spectral=True, init=init, regularizer=regularizer, scope=**layer**)
-> net = attention_block(net, spectral=True, init=init, regularizer=regularizer, scope=**layers**)

**Comment by AdalbertoCq** [comment]
Hey @YongtaeKim,
 
Thanks for bringing this up. I'll update the code.

Thanks,
Adal
