### ISSUE TITLE
AttributeError: 'Data' object has no attribute 'patch_h'

### ISSUE THREAD

**Issue by markemus** [AdalbertoCq/Pathology-GAN#3]
I'm getting this exception trying to run generate_fake_samples:

```
python3 generate_fake_samples.py --checkpoint ckpt/PathologyGAN.ckt.data-00000-of-00001 --num_samples 5 --z_dim 200 --main_path .
```

```
Traceback (most recent call last):
  File "generate_fake_samples.py", line 66, in <module>
    gen_hdf5_path = generate_samples_from_checkpoint(model=pathgan, data=data, data_out_path=main_path, checkpoint=checkpoint, num_samples=num_samples, batches=batch_size)
  File "/home/john/dev/Pathology-GAN-master/models/evaluation/features.py", line 165, in generate_samples_from_checkpoint
    res = 'h%s_w%s_n%s_zdim%s' % (data.patch_h, data.patch_w, data.n_channels, model.z_dim)
AttributeError: 'Data' object has no attribute 'patch_h'
```

I'm using the checkpoint and data files from the readme (generate_fake_samples wouldn't run without the data files).
checkpoint: https://figshare.com/s/0a311b5418f21ab2ebd4
data: https://drive.google.com/file/d/1LpgW85CVA48C8LnpmsDMdHqeCGHKsAxw/view

The only changes I made to the code is to change the import for tensorflow from tf.compat.v1 to tensorflow (with tensorflow 1.12.0 per the readme). Any help would be appreciated.

**Comment by AdalbertoCq** [comment]
Hey markemus,

The data/dataset were outdated. I pushed the latest version. Could you try again?

Thanks,
Adal

**Comment by markemus** [comment]
I redownloaded from the link in the readme but I got the same error. I'll try again after the weekend to confirm.

**Comment by AdalbertoCq** [comment]
Hi markemus,

By data/dataset I meant the python scripts in the repository, not the data or checkpoint.

Thanks,
Adal

**Comment by markemus** [comment]
Thank you, that seemed to fix that issue! I'm having a different bug now but I started a new issue for it.
