### ISSUE TITLE
Could not open ckpt/PathologyGAN.ckt.data-00000-of-00001 when running generate_fake_samples.py (Wrong tensorflow version?)

### ISSUE THREAD

**Issue by markemus** [AdalbertoCq/Pathology-GAN#4]
`2020-09-21 13:11:42.705754: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ckpt/PathologyGAN.ckt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?`

I think the issue might be the tensorflow version. The code imported tf.compat.v1 as tensorflow, but I changed it to import tensorflow since I have tf 1.12.0 installed per the documentation. Is the code actually in TF 2.0 now? If so which version in particular?

**Comment by AdalbertoCq** [comment]
Could you try to lead the weights providing the checkpoint as this?
**_--checkpoint path_to_your_checkpoint/PathologyGAN.ckt_**

I haven't updated the code to TensorFlow 2.0 yet.

Thanks,
Adal

**Comment by markemus** [comment]
It worked! And these patches are as beautiful as promised. Fantastic work, thank you so much.

**Comment by AdalbertoCq** [comment]
Cool, happy to help :)

Btw, do you mind if I ask what's your plan on how to use the images?

Thanks,
Adal

**Comment by markemus** [comment]
We're doing a study comparing different featurizing models for a pathology dataset and we wanted to have a GAN approach. PathologyGAN seemed to have the best generated images of the models we looked at. As for whether that corresponds to good featurization.... we shall see! :)
