### ISSUE TITLE
generate_fake_samples.py generates empty folder

### ISSUE THREAD

**Issue by nalrasheed** [AdalbertoCq/Pathology-GAN#5]
Hello!

I trained the model on my own images and trying to generate fake samples. However the generated_images/ is empty after running generate_fake_samples.py. Do you have any idea how to generate fake samples?

**Comment by AdalbertoCq** [comment]
Hi Nalrasheed,

Could you provide me some more information? Did you run a command similar to the one in the readme? What is the terminal output when you run it?

python3 ./generate_fake_samples.py --num_samples 100 --batch_size 50 --z_dim 200 --checkpoint data_model_output/PathologyGAN/h224_w224_n3_zdim_200/checkpoints/PathologyGAN.ckt --main_path path_for_folder_to_dump_evaluation --dbs_path path_to_main_folde_with_dataset_folder

Thanks,
Adal
