### ISSUE TITLE
typo on scope label for attention layer in generator.py

### ISSUE THREAD

**Issue by theodore-evans** [AdalbertoCq/Pathology-GAN#8]
While it does not affect functionality, I believe that the scope argument for attention_block inside the `for layer in range(layers)` loop of both generator_resnet_style and generator_resnet in generator.py should be scope=layer rather than scope=layers. 

This was confusing when trying to follow the order of operations by looking at the variable scopes in the checkpoint file, as it makes it seem that the attention block is reached after the central block of resnet and conv layers, rather than midway through.

```
# Attention layer. 
			if attention is not None and net.shape.as_list()[1]==attention:
				net = attention_block(net, spectral=True, init=init, regularizer=regularizer, scope=layers)
```

**Comment by AdalbertoCq** [comment]
Hi Theodore,

Thanks for the feedback. That makes sense, I changed the code to fix the typo. 

In case you want to check more details on the architecture, the Appendix I of the [paper](https://openreview.net/pdf?id=CwgSEEQkad) also contains details on the layers and order. 

Thanks,
Adal
